[package]
name = "logging_timer"
version = "0.2.2"
authors = ["Philip Daniels <Philip.Daniels1971@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PhilipDaniels/logging_timer"
description = "A simple timer that logs the elapsed time when dropped"
categories = ["development-tools::debugging"]
keywords = ["logging", "timer"]
documentation = "https://docs.rs/logging_timer/"

[dependencies]
log = "0.4"
